version: "3.2"
volumes:
  postgres:
services:
  web:
    build: .
    command: /code/run-container.sh
    environment:
      - DJANGO_SETTINGS_MODULE=fpdc.settings.base
      - PYTHONPATH=/code
    volumes:
      - .:/code:z
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata:z
